language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: D8Z2pmvfy0LETBW5A6xzdU/Q8dEkbVAptbofWZIpHEl4dWC6vVux3A5MeRIXp6Sv5n/Vyw4pIh+dXcUrrLtofhLksTLIEgeNpG6hC+ctMYMxW63U2skIxa6RQ8iZy5/qQ9btJH3hd4hJI3u2sQ2NgHpw/KCj1sRrT8aIrS9QQl4zxxLd8D8HPUlr3O/eV1Ik38quCPmmrp/6jRJnZnE1Y3IcNqt/L0CLsZwqued6WyqWBU/2yskGxmij5i88RPgxN1oau6HUtPW8lqJhwdnTOgi9/t9kDkItopPC25A6gSGwwI75gF1jvWe95aQQfqLwHnOZcjEEBs3836ibQT5PPTr9vtKLssH35uM22pAWIlP38zilOIVN4Jy3nYC983ef7ZtBLuBFBatmOUBYOrlFN4GdlVPUOcbZFsBnjQnDoSADJ+fDt6Q/WJ2knudfc82kle0Jul8fIKP5OIGLk1ZhhuBYkbM6k8l3offk/cRIhVI5D94zm2UJkw+8MAlP6ffcPNMUzCU9YofaB0lX3j5/JKwntph27VnNUsplsUtM0uOEtN+4VuzdzAXDnm1yp4fGObffrMUJ9coG+kEBYaKFoLgFoVv1H76Xn1FLWtbqBOnC6Se5FPoxYVD2eYMjNRuEP9sYs63jS0oYjWj+Z2z1rkH26BgyGcCZxCj7qTzvTwE=
  - secure: DTfPB0fMpchGnbeV5YVevVQBoqow1WCeSZqgjKigsVgkKTFhuX03Wnbjce7E669p2vioPclxrF6jvjegDZCexIjUYNRZhfNZtvaZ6/kzwOC9vlC9b+5WJ6XSG6gm7YZaQ2TP353c8bqBSyVW2LvECtwZZxM3x6pt8zA2UX100uh/+0Ftc3QbBoBXZkgaXfCT84P/OO52hPuZZl04u+TJabrwt3TPxRUIcxTrGUnW37wOPxyYt6qcFZplAmjorm6vFIcE0FNH90yViqEp3rKBtQGgDW0XnmoTYLRCEDDdRmTyGFoOjjnpZuaA41iiUJx6F3H63zAQOpB8mefjvYGKcnvIVHTHWfPOwNycSiATQ9g8QV5Z3y6HE+Kk5wDcL/USiOl4tn651s4eY+tE2sswpRyMfQa/f6x73xYT0Wqa22Xss4uzLtVJhxcZIku8pxDSJg40XQxSUXwuwfU3OJvNjsKVPjXnZ3QYrvQN7A6ZEDRw60BLQ+XVvlHSdLAeWPbtUWeUc1ke/x7QhTGIskkGlvV9AlW6LQDkfX5YwjQ9ZYCyAmfSjmN4J01oBQbbj+/XoS1iIna7VpWEEPbMw6sG+CF3jyk14EwmU2l8G3ZxtXBkzzCH5joIOTQZh8iUZ1BxTqBWlExHlcaUHJxG12udc/MLzkKUDIcOEIOlkzuwfhU=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- pip install --user codecov
script:
- mvn clean test -B
- mvn clean test -B -Dfasterxml.version=2.8.4
after_success:
- codecov
- mvn clean deploy -DskipTests --settings .travis/maven-settings.xml